# Generated by Django 2.0.4 on 2018-04-11 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('weight', models.PositiveSmallIntegerField()),
                ('height', models.PositiveSmallIntegerField()),
                ('goal', models.CharField(choices=[('LW', 'Lose Weight'), ('MW', 'Maintain Weight'), ('GW', 'Gain Weight')], default='MW', max_length=2)),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'female')], default='F', max_length=1)),
                ('date_of_birth', models.DateField()),
                ('activity_level', models.CharField(choices=[('S', 'Sedentary'), ('LA', 'Lightly Active'), ('A', 'Active'), ('VA', 'Very Active')], default='LA', max_length=2)),
                ('workouts_per_week', models.PositiveSmallIntegerField()),
                ('workout_minutes', models.PositiveSmallIntegerField()),
                ('date_signed_up', models.DateTimeField(auto_now_add=True)),
                ('password', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
