"""added a model for recipes

Revision ID: 4b77a07ea807
Revises: 5742e0504794
Create Date: 2018-04-16 12:50:51.735254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b77a07ea807'
down_revision = '5742e0504794'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('input_recipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('servings', sa.Integer(), nullable=True),
    sa.Column('ingredients', sa.String(length=10000), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('input_recipe')
    # ### end Alembic commands ###
