"""added image to user submitted recipe

Revision ID: f536637e04b1
Revises: 4b77a07ea807
Create Date: 2018-05-03 15:50:39.608572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f536637e04b1'
down_revision = '4b77a07ea807'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('input_recipe', sa.Column('picture_url', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('input_recipe', 'picture_url')
    # ### end Alembic commands ###
